version: "3"
services:
  server:
    container_name: docker-rest-dish-back
    restart: always
    build: ./backend
    ports: 
      - "5000:5000"
  #   links: -mongo
  # mongo:
  #   container_name: mongo
  #   image: mongo
  #   ports: -"27017:27017"
  client:
    container_name: docker-rest-dish-front
    restart: always
    build: ./frontend
    ports: 
      - "3000:3000"
    links: 
      - server
