const ENQUEUE_SNACKBAR = "ENQUEUE_SNACKBAR";
const REMOVE_SNACKBAR = "REMOVE_SNACKBAR";
const LOADING = "USER_LOADING";
const SET_CURRENT_USER = "SET_CURRENT_USER";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_FAIL = "REGISTER_FAIL";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAIL = "LOGIN_FAIL";
const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
const AUTH_ERROR = "AUTH_ERROR";
const REMOVE_CURRENT_USER = "REMOVE_CURRENT_USER";
const GET_USER_DISHES = "GET_USER_DISHES";
const ADD_USER_DISHES = "ADD_USER_DISHES";
const USER_LOGOUT = "USER_LOGOUT";
const DELETE_USER_DISHES = "DELETE_USER_DISHES";
const GET_ALL_DISHES = "GET_ALL_DISHES";
const ADD_USER_DISH_INGREDIENT = "ADD_USER_DISH_INGREDIENT";
const GET_DISH = "GET_DISH";
const GET_ALL_COMMENTS = "GET_ALL_COMMENTS";
const POST_COMMENT = "POST_COMMENT";
const SUBMIT_RATING = "SUBMIT_RATING";
const POST_ORDER = "POST_ORDER";
const ADD_TO_CART = "ADD_TO_CART";
const GET_CART_ITEMS = "GET_CART_ITEMS";
const EDIT_CART = "EDIT_CART";
const GET_ORDER_ITEMS = "GET_ORDER_ITEMS";
const ORDER_COMPLETED = "ORDER_COMPLETED";
export {
  ORDER_COMPLETED,
  GET_ORDER_ITEMS,
  ENQUEUE_SNACKBAR,
  REMOVE_SNACKBAR,
  LOADING,
  SET_CURRENT_USER,
  REGISTER_SUCCESS,
  REGISTER_FAIL,
  LOGIN_SUCCESS,
  LOGIN_FAIL,
  LOGOUT_SUCCESS,
  AUTH_ERROR,
  REMOVE_CURRENT_USER,
  GET_USER_DISHES,
  ADD_USER_DISHES,
  USER_LOGOUT,
  DELETE_USER_DISHES,
  GET_ALL_DISHES,
  ADD_USER_DISH_INGREDIENT,
  GET_DISH,
  GET_ALL_COMMENTS,
  POST_COMMENT,
  SUBMIT_RATING,
  POST_ORDER,
  ADD_TO_CART,
  GET_CART_ITEMS,
  EDIT_CART
};
